import type { SponsorConfig } from "../types/config";

export const sponsorConfig: SponsorConfig = {
	title: "方舟飞升生物皮肤赞助计划",
	description: "参与方舟飞升生物皮肤赞助，支持我们继续为游戏中的经典生物制作全新的科技风格皮肤。",
	usage: "您的赞助将用于服务器维护、内容创作和功能开发，帮助我们持续提供优质内容。",
	showSponsorsList: true,
	showComment: true,
	showButtonInPost: true,
	methods: [
		{
			name: "支付宝",
			icon: "fa7-brands:alipay",
			qrCode: "/assets/images/sponsor/alipay2.png",
			link: "",
			description: "使用 支付宝 扫码赞助",
			enabled: true,
		},
		{
			name: "微信",
			icon: "fa7-brands:weixin",
			qrCode: "/assets/images/sponsor/wechat2.png",
			link: "",
			description: "使用 微信 扫码赞助",
			enabled: true,
		},
		{
			name: "ko-fi",
			icon: "simple-icons:kofi",
			qrCode: "https://ko-fi.com/shinalena",
			link: "",
			description: "Buy a Coffee for Firefly",
			enabled: true,
		},
		{
			name: "爱发电",
			icon: "simple-icons:afdian",
			qrCode: "",
			link: "https://www.ifdian.net/a/Lena_Bai",
			description: "通过 爱发电 进行赞助",
			enabled: true,
		},
	],
	sponsors: [
		{ name: "道九闲歌", amount: "感谢支持", date: "2026-05-19" },
		{ name: "匿名用户", amount: "感谢支持", date: "2025-10-01" },
		{ name: "旦那曦曦", amount: "感谢支持", date: "2026-05-14" },
		{ name: "琳", amount: "感谢支持", date: "2026-05-17" },
		{ name: "lost-", amount: "感谢支持", date: "2026-04-30" },
		{ name: "月翻", amount: "感谢支持", date: "2026-04-09" },
		{ name: "扑朔迷离", amount: "感谢支持", date: "2026-05-22" },
		{ name: "仙于点威", amount: "感谢支持", date: "2026-05-22" },
		{ name: "石黑英雄红凯", amount: "感谢支持", date: "2026-05-22" },
		{ name: "烤面包机", amount: "感谢支持", date: "2026-05-22" },
		{ name: "琪晓雯", amount: "感谢支持", date: "2026-05-22" },
		{ name: "水月", amount: "感谢支持", date: "2026-05-22" },
		{ name: "♋0%的苏拉", amount: "感谢支持", date: "2026-05-22" },
		{ name: "链路雀", amount: "感谢支持", date: "2026-05-22" },
		{ name: "尹", amount: "感谢支持", date: "2026-05-22" },
		{ name: "《CENSORED》", amount: "感谢支持", date: "2026-05-22" },
		{ name: "昔漓", amount: "感谢支持", date: "2026-05-22" },
		{ name: "danten", amount: "感谢支持", date: "2026-05-22" },
		{ name: "寂如夜静如水", amount: "感谢支持", date: "2026-05-22" },
	],
};
